### ISSUE TITLE
to import this package at android and ios

### ISSUE THREAD

**Issue by hatano0x06** [tomaschyly/web_browser_detect#1]
I think this is great package

but this code, doesn't allow to import at android and ios
https://github.com/tomaschyly/web_browser_detect/blob/master/lib/browser.dart#L1

if you change to 
```
import 'package:universal_html/html.dart';
```
this package will be allow to import at android and ios too

**Comment by tomaschyly** [comment]
Hi,
I did actually use it at first, but I felt like I was lying to people. You cannot use it on mobile anyway, it detects only browser in which Flutter web is running.

Can you explain to me a reason why I should do it anyway? Will it help you in some way? I will consider it.

Thank you for your feedback.

**Comment by hatano0x06** [comment]
This package is not implemented for android and ios.
So if developer what to use this package at android and ios, "implement error" will occur.

It is clearly wrtttin in pub.dev  that this package can only be used on the web
https://pub.dev/packages/web_browser_detect

So, I don't think about lying


I use this package for the data collection part when making inquiries
This part is a process that passes through android, ios, and the web.

Therefore, if I use this package, an error will occur on android, ios.

**Comment by tomaschyly** [comment]
I have release v1.0.3 on pub.dev where I have changed to universal_html.
I dont have time right now to test it thoroughly, can you check if it works for you and let me know?

**Comment by hatano0x06** [comment]
I will try to check it this week, and if these is a problem, I will make a issue! 
thank you!
