### ISSUE TITLE
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/web_browser_detect-2.0.1/lib/src/browser.dart:43:36: Warning: Operand of null-aware operation '??' has type 'String' which excludes null. appVersion: window.navigator.appVersion ?? '', // The ?? are because of bug when building for mobile

### ISSUE THREAD

**Issue by dgurudot** [tomaschyly/web_browser_detect#3]
Getting this warning when running simple example app

**Comment by tomaschyly** [comment]
This is a known issue that does not affect anything.
There is an inconsistency where on web the appVersion is String, but on mobile it is String?
If I remove ?? then you will not be able to compile for any other platform then web.

If it bothers you, I can camouflage it with some added checks.

**Comment by tomaschyly** [comment]
Check web_browser_detect: ^2.0.2
